### ISSUE TITLE
These new "threshold bars" are a pain in the a** to use :-(

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#23] opened 2019-04-01 19:20 UTC
I cannot use them to properly set some values.
Please revert to good-old fields instead of bars. 
Thanks

![1](https://user-images.githubusercontent.com/5783257/55353573-efcc2480-54c3-11e9-9a0c-9594e9111028.png)

**Comment by Tucsky** [comment] 2019-04-01 19:24
Ty for reporting that! May I ask what kind of browser you are using to get
such a distorted layout ? Is it on mobile ?
I might add a switch to display threshold either in slider mode (current)
and table mode.

―
Kevin Rostagni
+33 6 66 44 56 88
kevinrostagni.codes

**Comment by Tucsky** [comment] 2019-04-01 19:27
It should look like this
![image](https://user-images.githubusercontent.com/5738336/55353971-d9729880-54c4-11e9-945f-353ce083210e.png)

**Comment by rranke** [comment] 2019-04-01 19:30
Yes, normally it looks like your screenshot. But after playing with the bars, a trying to enter some values (numbers) these four small white balls are just not doing what i want :-(


I am using firefox on desktop ubuntu.

![2](https://user-images.githubusercontent.com/5783257/55353952-c8298c00-54c4-11e9-9f66-c59906d6870d.png)

But window-size is "mobile-like" (responsive)

![3](https://user-images.githubusercontent.com/5783257/55354052-0921a080-54c5-11e9-9862-514c7c7892ec.png)

**Comment by rranke** [comment] 2019-04-01 19:32
Yes, an option for either "slider (new)" or good old "fields (old)" would be great.
Thanks

**Comment by Tucsky** [comment] 2019-04-01 19:51
The only way I can reproduce it right now is by setting "0" manualy to one of the threshold and reload the page, then its broken and the only way to get it working again is by setting a valid threshold manualy to each "corrupted" thresholds using this field
![image](https://user-images.githubusercontent.com/5738336/55355115-bc8b9480-54c7-11e9-96a4-f2a0312da033.png)

Allowing 0 is a bug (or anything other than a >0 number) and will be fixed shortly 💯 
Im assuming you did not set the value manualy to 0 tho, so im installing linux rn see where the problem is.

**Comment by rranke** [comment] 2019-04-01 20:00
- Are new entered values accepted after clicking "enter" or what do i have to do to set values?

- Moving these white dots / entering values is still buggy, or at least, feels buggy, i would say, all in all a good idea, but seems over-engineered, or to complex / not "easy-to-use" for the "normal" user

**Comment by Tucsky** [comment] 2019-04-02 11:00
> Are new entered values accepted after clicking "enter" or what do i have to do to set values?
Ive just added the validation of the value (threshold) by pressing enter, before you had to click outside of the element so it lose focus and trigger the save. Its much better now thank you :)

> Moving these white dots / entering values is still buggy, or at least, feels buggy, i would say, all in all a good idea, but seems over-engineered, or to complex / not "easy-to-use" for the "normal" user
The normal use might use a normal browser on a normal OS, tho, so less likely to be buggy since it works very smoothly pretty smoothly on chrome / firefox / windows & osx. Nothing against linux thats just the way it is :)

Ive added the touch support and <=0 threshold bug should be fixed by now. table view soon

**Comment by rranke** [comment] 2019-04-02 13:28
- "pressing enter" -> okay, super!
- Nahhh, it works great now on linux/firefox!

Should be fine now.

**Closed** 2019-04-06 18:48 UTC
